CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_DE_MUSICA_2ANO;
USE BD_APLICATIVO_DE_MUSICA_2ANO;

CREATE TABLE IF NOT EXISTS ARTISTA(
	DOCUMENTO VARCHAR (14) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    FOTO BLOB,
    EMAIL VARCHAR (255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FOTO BLOB,
    TIPO_MUSICA VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FOTO BLOB,
    NOME VARCHAR (255) NOT NULL,
    PRODUTOR VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (255),
    DATA_LANCAMENTO DATE NOT NULL,
    FK_DOCUMENTO_ARTISTA VARCHAR (20) NOT NULL,
    FOREIGN KEY (FK_DOCUMENTO_ARTISTA) REFERENCES ARTISTA(DOCUMENTO)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LETRA VARCHAR (2000) NOT NULL,
    FOTO BLOB,
    DURACAO INTEGER NOT NULL,
    FK_ID_ALBUM INTEGER NOT NULL,
    FK_ID_GENERO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO (ID)
);