CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA_2ANO;
USE BD_BIBLIOTECA_2ANO;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR (15) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    FOTO BLOB,
    GENERO_LIVRO VARCHAR (255) NOT NULL,
    LIVROS_PUBLI VARCHAR (255)
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    CATEGORIA VARCHAR (255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR (15) PRIMARY KEY,
    EMAIL VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (20),
    NOME VARCHAR (255) NOT NULL,
    DATA_NASCI DATE NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS ACESSAR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CPF_LEITOR VARCHAR (15) NOT NULL,
    FK_ID_LIVRO_DIGITAL INTEGER NOT NULL,
	FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE,
	FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE
);

DROP DATABASE BD_BIBLIOTECA_2ANO