CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_2ANO;
USE BD_CONSULTAS_2ANO;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR (10) PRIMARY KEY,
    CPF VARCHAR (15) NOT NULL,
    RG VARCHAR (15) NOT NULL,
    NOME VARCHAR (255) NOT NULL,
    TELEFONE VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR (15) PRIMARY KEY,
    RG VARCHAR (15) NOT NULL,
    NOME VARCHAR (255) NOT NULL, 
    FOTO BLOB,
    DATA_NASCI DATE NOT NULL,
    TELEFONE VARCHAR (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTAS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_CONSULTA DATE NOT NULL,
    NOME_MEDICO VARCHAR (255) NOT NULL,
    NOME_PACIENTE VARCHAR (255) NOT NULL, 
    FK_CRM_MEDICO VARCHAR (10) NOT NULL,
    FK_CPF_PACIENTE VARCHAR (15) NOT NULL,
	FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
	FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);