CREATE DATABASE IF NOT EXISTS BD_PROJETOS_2ANO;
USE  BD_PROJETOS_2ANO;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    ENTREGA DATE NOT NULL, 
    DESCRICAO VARCHAR (255) NOT NULL,
    QUANTIDADE INTEGER
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR (15) PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFAS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR (255) NOT NULL,
    PRAZO DATE NOT NULL,
    FK_CPF_FUNCIONARIO VARCHAR (15) NOT NULL,
    FK_ID_PROJETO INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE
);