CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS_2ANO;
USE BD_RESERVAS_AEREAS_2ANO;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR (15) PRIMARY KEY,
    PASSAPORTE VARCHAR (255) NOT NULL, 
    NOME VARCHAR (255) NOT NULL,
    IDADE INTEGER,
    TELEFONE VARCHAR (40)
);

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LUGAR_IDA VARCHAR (255) NOT NULL,
    LUGAR_VOLTA VARCHAR (255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOCALIDADE VARCHAR (255),
    FK_CPF_PASSAGEIRO VARCHAR (15) NOT NULL,
    FK_ID_VOO INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE
);