CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_2ANO;
USE BD_ALUGUEL_2ANO;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR (14) NOT NULL, 
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR (255) NOT NULL,
    DESCRICAO VARCHAR (500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL,
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE 
);

-- DML - LINGUAGEM DE MANIPULAÇÃO 
-- INSERT - INSERIR
INSERT INTO CLIENTE (EMAIL, TELEFONE, CPF, NOME)
VALUES ("email@email.com","19999999999","123456789","eu");

INSERT INTO CLIENTE (EMAIL, TELEFONE, CPF, NOME)
VALUES ("diego.vielbortolotti@gmail.com","19991608631","45050939801","Diego");

INSERT INTO CLIENTE (NOME, EMAIL, TELEFONE, CPF)
VALUES ("Diego","diego.vielbortolotti@gmail.com","19991608631","50040039");

-- SELECT - SELECIONAR 
SELECT * FROM CLIENTE;

-- INSERIR PRODUTOS
INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("macbook m4","notebook apple",4789.90,5);

-- INSERINDO 10 PRODUTOS

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("macbook m4","notebook apple",4789.90,5);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Notebook Dell Inspiron","Notebook da dell",3500,12);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Smartphone Samsung Galaxy A54","Galaxy A54",1899,20);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Fone de Ouvido Bluetooth JBL Tune 510BT"," Fone de ouvido",279,35);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Televisão LG 50” 4K UHD","TV 4K",2400,8);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Mochila Lenovo Casual","mochila",150,50);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Teclado Mecânico Redragon Kumara","teclado",230,18);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Mouse Sem Fio Logitech M170","mouse sem fio",80,40);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Cadeira Gamer ThunderX3","cadeira gamer",1200,10);

INSERT INTO PRODUTO (NOME,DESCRICAO,PRECO,QTD_DISPONIVEL)
VALUES ("Impressora Multifuncional HP DeskJet 2776","impressora",420,15);

SELECT * FROM PRODUTO;

-- INSERIR ALUGUEIS
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (DATA_ALUGUEL,
					 DATA_DEVOLUCAO,
                     VALOR_TOTAL,
                     FK_CLIENTE_ID,
                     FK_PRODUTO_ID)
VALUES              ("2025-09-24",
					 "2025-10-01",
                     7890,
                     3,
                     11);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",1250,3,1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2026-01-01","2026-02-4",1250,1,9);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",750,4,11);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",50,4,10);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-9-21","2025-10-9",900,4,7);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",750,4,11);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",590,2,3);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-25","2025-10-9",750,4,11);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-9","2025-10-9",40,2,9);

-- OUTROS 10 Q N RODEI

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",1250,3,1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2026-01-01","2026-02-4",1250,1,9);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",750,4,11);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",50,4,10);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-9-21","2025-10-9",900,4,7);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-9",750,4,11);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-01","2025-10-7",590,2,3);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-7-25","2025-8-9",790,4,1);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-10-9","2025-10-9",40,2,6);

INSERT INTO ALUGUEL (DATA_ALUGUEL,DATA_DEVOLUCAO,VALOR_TOTAL,FK_CLIENTE_ID,FK_PRODUTO_ID)
VALUES ("2025-12-9","2026-10-9",40,2,6);

SELECT * FROM ALUGUEL;
SELECT * FROM PRODUTO;

-- ATUALIZAR UM REGISTRO (UPDATE)
UPDATE PRODUTO
SET    PRECO = 3500
WHERE PRODUTO_ID = 1;

UPDATE PRODUTO
SET    PRECO = 500
WHERE PRODUTO_ID = 11;

UPDATE PRODUTO
SET    PRECO = 00
WHERE PRODUTO_ID = 11;

-- ESTOQUE

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 10
WHERE PRODUTO_ID = 3;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 9
WHERE PRODUTO_ID = 4;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 1
WHERE PRODUTO_ID = 5;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 3
WHERE PRODUTO_ID = 6;

UPDATE PRODUTO
SET    QTD_DISPONIVEL = 35
WHERE PRODUTO_ID = 7;

-- 2 EMAIL

UPDATE CLIENTE
SET    EMAIL = "junior@hotmail.com"
WHERE CLIENTE_ID = 2;

UPDATE CLIENTE
SET    EMAIL = "felipedoadordecaneco@yahoo.com"
WHERE CLIENTE_ID = 1;

SELECT * FROM CLIENTE;

-- DATA DE DEVOLUÇÃO 

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2025-12-25"
WHERE ALUGUEL_ID = 1;

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2025-12-26"
WHERE ALUGUEL_ID = 2;

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2025-12-27"
WHERE ALUGUEL_ID = 3;

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2025-12-28"
WHERE ALUGUEL_ID = 4;

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2025-12-29"
WHERE ALUGUEL_ID = 5;

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2025-12-30"
WHERE ALUGUEL_ID = 6;

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2025-12-31"
WHERE ALUGUEL_ID = 7;

UPDATE ALUGUEL
SET    DATA_DEVOLUCAO = "2026-01-01"
WHERE ALUGUEL_ID = 8;


SELECT * FROM ALUGUEL;

-- APAGAR UM REGISTRO (DELETE)
DELETE FROM CLIENTE 
WHERE CLIENTE_ID = 1;

DELETE FROM PRODUTO
WHERE       PRODUTO_ID = 4;

DELETE FROM ALUGUEL
WHERE       ALUGUEL_ID = 3;

SELECT * FROM CLIENTE;

SELECT * 
FROM CLIENTE 
WHERE CLIENTE_ID = 2;

SELECT NOME,PRECO
FROM PRODUTO
WHERE PRODUTO_ID = 3;