CREATE DATABASE IF NOT EXISTS BD_ENQUETES_2ANO;
USE BD_ENQUETES_2ANO;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR (200),
    USU_AREA_FORMACAO VARCHAR (500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MÉDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENG_DATA_FINAL DATE, 
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(300) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (ENQ_CODIGO),
	FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT, 
    RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO 
(USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES
("2025-10-01", "joao123", "Tecnologia da Informação", "Desenvolvedor", "Ciência da Computação", "1995-05-10", "SOLTEIRO", "SP", "SUPERIOR", "joao123@email.com", "senha123", "João Silva"),
("2025-10-01", "maria_costa", "Educação", "Professora", "Pedagogia", "1988-03-22", "CASADO", "RJ", "SUPERIOR", "maria.costa@email.com", "senha456", "Maria Costa"),
("2025-10-01", "carlos_ti", "Suporte Técnico", "Analista de Suporte", "Redes de Computadores", "1990-12-15", "DIVORCIADO", "MG", "MÉDIO", "carlos.ti@email.com", "senha789", "Carlos Pereira");

INSERT INTO ENQUETE 
(ENG_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES
("2025-12-31", "2025-10-01", "Enquete sobre preferências de tecnologia", "Preferências Tech", 1),
("2025-12-12", "2025-10-05", "Pesquisa sobre hábitos de estudo", "Estudo e Rotina", 2),
("2026-01-15", "2025-10-10", "Opinião sobre tendências de carreira", "Futuro Profissional", 3);

INSERT INTO USUARIO_RESPONDE_ENQUETE 
(URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES
("2025-10-01", 1, 1),
("2025-10-02", 2, 1),
("2025-10-03", 3, 2);

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES
("Você gosta de programar?", 1),
("Quantas horas por semana você estuda?", 2),
("Você pretende mudar de área nos próximos 5 anos?", 3);

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES
("Sim", "S", 1),
("Não", "N", 1),

("0-5 horas", "N", 2),
("6-10 horas", "N", 2),
("Mais de 10 horas", "N", 2),

("Sim", "S", 3),
("Não", "N", 3);
DROP DATABASE BD_ENQUETES_2ANO;
